[aws]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

[username]
show_always = true

[battery]
charging_symbol = "âš¡ï¸"

[directory]
truncate_to_repo = false

[hostname]
ssh_only = false

[golang]
symbol = "î˜¦ "
